- name: SonarScanner Begin
  run: |
    dotnet sonarscanner begin `
      /k:"<Project Key>" `
      /o:"<Organization Key>" `
      /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
      /d:sonar.qualitygate.wait=true
  shell: pwsh
